### ISSUE TITLE
System.ObjectDisposedException: 'Cannot access a closed Stream.'

### ISSUE THREAD

**Issue by pkr-sadx** [CollapseLauncher/Hi3Helper.SharpHDiffPatch#4]
Hi! I ran into this exception (PatchDir.cs line 95) while trying to patch a folder with a bunch of files. It works with the C++ version so I thought I should report this.

[Files and patch](https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Various/test.7z)

I used the following code to reproduce it:
```
 HDiffPatch patcher = new HDiffPatch();
 patcher.Initialize("D:\\diff\\test.dat");
 Directory.CreateDirectory(Path.Combine(AppContext.BaseDirectory, "temp"));
 patcher.Patch("D:\\diff\\in", Path.Combine(AppContext.BaseDirectory, "temp"), false, default, false, true);
```

**Comment by neon-nyan** [comment]
Thank you for reporting the issue. will try to investigate this.

**Comment by neon-nyan** [comment]
Hi there
I just pushed a commit that hopefully fix the issue. It was caused by the ``BZip2`` input stream disposing the source ``FileStream`` too early when it's reaching EoF.
Let me know if it fixes the issue for you.

**Comment by pkr-sadx** [comment]
Hi! Thank you for the quick response and the fix. The data is now patched without errors.
